<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Jarvis.Api</AssemblyName>
    <RootNamespace>Jarvis.Api</RootNamespace>
    <UserSecretsId>Jarvis.Api-e06d4bd7-6d95-4129-9f28-cc7520010f9f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <ProjectReference Include="../Jarvis.Application/Jarvis.Application.csproj" />
    <ProjectReference Include="../Jarvis.Infrastructure/Jarvis.Infrastructure.csproj" />
    <ProjectReference Include="../Jarvis.Contracts/Jarvis.Contracts.csproj" />
  </ItemGroup>
</Project>
