// <auto-generated />
using System;
using Jarvis.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jarvis.Infrastructure.Data.Migrations
{
    [DbContext(typeof(JarvisDbContext))]
    [Migration("20260826025116_Phase5SummariesMemory")]
    partial class Phase5SummariesMemory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Jarvis.Domain.Approvals.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DecidedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DecidedByDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Decision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpiresAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedActionJson")
                        .IsRequired()
                        .HasMaxLength(1000000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("DeviceId", "RequestId")
                        .IsUnique();

                    b.HasIndex("TaskId", "Status", "CreatedAtMs");

                    b.ToTable("Approvals", (string)null);
                });

            modelBuilder.Entity("Jarvis.Domain.Conversations.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CurrentSummaryId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastActivityAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LastActivityAtMs");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("Jarvis.Domain.Conversations.ConversationSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FromSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("TEXT");

                    b.Property<long>("ToSequence")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "ToSequence");

                    b.ToTable("ConversationSummaries", (string)null);
                });

            modelBuilder.Entity("Jarvis.Domain.Conversations.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientRequestId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalItemId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InputModality")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputModality")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RealtimeSessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "ExternalItemId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique();

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Jarvis.Domain.Conversations.RealtimeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ConnectedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContextVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DisconnectedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalSessionId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FailedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RotatedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<string>("Voice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ExternalSessionId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "StartedAtMs");

                    b.ToTable("RealtimeSessions", (string)null);
                });

            modelBuilder.Entity("Jarvis.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedRootsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialHash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSeenAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("PairedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Jarvis.Domain.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("UserId", "Scope", "IdempotencyKey");

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("Jarvis.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Jarvis.Domain.Memory.MemoryFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastConfirmedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sensitive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceMessageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SupersedesMemoryId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("SourceMessageId");

                    b.HasIndex("SupersedesMemoryId");

                    b.HasIndex("UserId", "Key")
                        .IsUnique()
                        .HasFilter("Status = 0");

                    b.HasIndex("UserId", "Status", "UpdatedAtMs");

                    b.ToTable("MemoryFacts", (string)null);
                });

            modelBuilder.Entity("Jarvis.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ActionedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApprovalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeliveredAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExpiresAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReadAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("ApprovalId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId", "DedupKey")
                        .IsUnique();

                    b.HasIndex("UserId", "Status", "CreatedAtMs");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Jarvis.Domain.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ClaimedBy")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClaimedUntilMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("NextAttemptAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PublishedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("PublishedAtMs", "NextAttemptAtMs", "ClaimedUntilMs");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Jarvis.Domain.Tasks.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentRefsJson")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CapabilityEnvelopeJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<long?>("CompletedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CreatedByMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedOutput")
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("HeartbeatAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LeaseExpiresAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PreferredDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgressSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredCapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultPayloadJson")
                        .HasMaxLength(1000000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<int>("WorkerKind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDeviceId");

                    b.HasIndex("PreferredDeviceId");

                    b.HasIndex("ConversationId", "Status", "CreatedAtMs");

                    b.HasIndex("UserId", "Status", "CreatedAtMs");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("Jarvis.Domain.Tasks.TaskEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientEventId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "Sequence")
                        .IsUnique();

                    b.HasIndex("TaskId", "DeviceId", "ClientEventId")
                        .IsUnique();

                    b.ToTable("TaskEvents", (string)null);
                });

            modelBuilder.Entity("Jarvis.Domain.Tasks.TaskExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactManifestJson")
                        .IsRequired()
                        .HasMaxLength(1000000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodexThreadId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodexTurnId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CodexTurnStartRequestedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalExecutionId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultPayloadJson")
                        .HasMaxLength(1000000)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<int>("WorkerKind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskId", "Status");

                    b.ToTable("TaskExecutions", (string)null);
                });

            modelBuilder.Entity("Jarvis.Domain.Approvals.Approval", b =>
                {
                    b.HasOne("Jarvis.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jarvis.Domain.Tasks.TaskExecution", null)
                        .WithMany()
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Jarvis.Domain.Tasks.Task", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jarvis.Domain.Conversations.Conversation", b =>
                {
                    b.HasOne("Jarvis.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jarvis.Domain.Conversations.ConversationSummary", b =>
                {
                    b.HasOne("Jarvis.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jarvis.Domain.Conversations.Message", b =>
                {
                    b.HasOne("Jarvis.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jarvis.Domain.Conversations.RealtimeSession", b =>
                {
                    b.HasOne("Jarvis.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jarvis.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Jarvis.Domain.Devices.Device", b =>
                {
                    b.HasOne("Jarvis.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jarvis.Domain.Idempotency.IdempotencyRecord", b =>
                {
                    b.HasOne("Jarvis.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jarvis.Domain.Memory.MemoryFact", b =>
                {
                    b.HasOne("Jarvis.Domain.Conversations.Message", null)
                        .WithMany()
                        .HasForeignKey("SourceMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jarvis.Domain.Memory.MemoryFact", null)
                        .WithMany()
                        .HasForeignKey("SupersedesMemoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jarvis.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jarvis.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("Jarvis.Domain.Approvals.Approval", null)
                        .WithMany()
                        .HasForeignKey("ApprovalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Jarvis.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Jarvis.Domain.Tasks.Task", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Jarvis.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jarvis.Domain.Tasks.Task", b =>
                {
                    b.HasOne("Jarvis.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("AssignedDeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jarvis.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jarvis.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("PreferredDeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jarvis.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jarvis.Domain.Tasks.TaskEvent", b =>
                {
                    b.HasOne("Jarvis.Domain.Tasks.Task", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jarvis.Domain.Tasks.TaskExecution", b =>
                {
                    b.HasOne("Jarvis.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jarvis.Domain.Tasks.Task", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
